baseURL = "https://zplugin.github.io/"
languageCode = "en"
title = "Zsh Plugins | ‚ùÆ ZI ‚ùØ"
theme = "github-style"
googleAnalytics = ""
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
author = "Z-Shell Community"
description = "Zsh Plugins"
#  github = "z-shell"
#  facebook = ""
#twitter = "zshell_zi"
#  linkedin = ""
#  instagram = ""
#  tumblr = ""
email = "zplugin@zshell.dev"
#url = "https://z.digitalclouds.dev"
keywords = "Zsh Plugins"
rss = false
lastmod = true
userStatusEmoji = "üßô‚Äç‚ôÇÔ∏è"
favicon = "images/avatar.png"
location = ""
enableGitalk = false

[params.gitalk]
#clientID = ""
#clientSecret = ""
#repo = "github.zshell.dev"
#owner = "z-shell"
#admin = "ss-o"
#id = "location.pathname"
#labels = "gitalk"
#perPage = 15
#pagerDirection = "last"
#createIssueManually = false
#distractionFreeMode = false
[[params.links]]
title = "Z-Shell"
href = "https://github.com/z-shell"
icon = "https://github.com/z-shell.png"

[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]
